/* 
STACK - IT IS MEMORY THAT IS USE D FOR PRIMITUVE DATA TYPE LIKE : NUMBER BOOLEAN STRING BIGINT NULL UNDEFINED
SO ORIGINAL VALUE DOESNT CHANGE THE COY OF THE ADDRESS FROM THE ORIGINAL ADDRESS OR LOCATION
[CALL BY REFERENCE]
*/          
/* 
HEAP - IT IS MEMORY IS WHICH IS USED BY NON PRIMITIVE DATA TYPE LIKE - ARRAY OBJECT FUNCATION
IN THIS ORIGINAL VALUE CHANGES NO COPY OF ADDRESS SEND.... IF VALUE IS MODIFIED THEN 
ORGINAL VALUE WILL BE MODIFY..
[CALL BY REFERENCE]
*/